# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'WMT QE Shared Task 2022'
#tagline:          'A Jekyll theme'
description:      'Automatic methods for estimating the quality of MT output at run-time.'
url:               https://github.com/WMT-QE-Task/wmt-qe-2022/
baseurl:           https://github.com/WMT-QE-Task/wmt-qe-2022/

#author:
#  name:           'Mark Otto'
#  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2022

github:
  repo:           https://github.com/WMT-QE-Task/wmt-qe-2022/
